name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]
    steps:
      - name: "Checkout project"
        uses: actions/checkout@v2
        
      - name: "Select the latest stable Xcode 12"
        uses: devbotsxyz/xcode-select@v1
        with:
          version: "12"

      - name: Install dependencies
        run: brew install libsodium

      - name: "Build 'PWS-Grantor'"
        uses: devbotsxyz/xcode-archive@v1
        with:
          scheme: "PWS-Grantor"

      - name: "Build 'PWS-Requestor'"
        uses: devbotsxyz/xcode-archive@v1
        with:
          scheme: "PWS-Requestor"
